#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script

xrdb -load /etc/X11/Xresources/Xresources
xsetroot -solid "#99b3ff" &
openbox
