#!/bin/bash

# Define default values for parameters
export GEOMETRY=${GEOMETRY:-1600x800}
export RFBPORT=${RFBPORT:-5900}
export DISPLAY=${DISPLAY::0}

# Create USER if needed
if ! [ -z ${USERNAME+x} ]; then
  useradd ${USERID:+-u ${USERID}} ${USERNAME}
else
  USERNAME=$(whoami) # Should default to root
fi

# Start X and VNC server
su ${USERNAME} -c "xinit /etc/X11/xinit/xinitrc -- /usr/bin/Xvnc -desktop X -auth /root/.Xauthority -geometry 1600x800 -SecurityTypes none -depth 24 -rfbwait 120000 -rfbport 5900"
